embeddings {
  tensor_name: "GAT_pooled:00010"
  metadata_path: "00010/GAT_pooled/metadata.tsv"
  tensor_path: "00010/GAT_pooled/tensors.tsv"
}
embeddings {
  tensor_name: "GAT_features:00010"
  metadata_path: "00010/GAT_features/metadata.tsv"
  tensor_path: "00010/GAT_features/tensors.tsv"
}
embeddings {
  tensor_name: "GAT_MLP:00010"
  metadata_path: "00010/GAT_MLP/metadata.tsv"
  tensor_path: "00010/GAT_MLP/tensors.tsv"
}
embeddings {
  tensor_name: "GAT_pooled:00020"
  metadata_path: "00020/GAT_pooled/metadata.tsv"
  tensor_path: "00020/GAT_pooled/tensors.tsv"
}
embeddings {
  tensor_name: "GAT_features:00020"
  metadata_path: "00020/GAT_features/metadata.tsv"
  tensor_path: "00020/GAT_features/tensors.tsv"
}
embeddings {
  tensor_name: "GAT_MLP:00020"
  metadata_path: "00020/GAT_MLP/metadata.tsv"
  tensor_path: "00020/GAT_MLP/tensors.tsv"
}
